### ISSUE TITLE
Iterators convention

### ISSUE THREAD

**Issue by Augustyn** [darkonion/SortingComparator#2]
This is trivial and not issue at all, because code is correct. But as a convention iterators starts with letter `i` as _iterator_, next is `j`, `k` etc. Your iterators starts with `m`, ex:

https://github.com/darkonion/SortingComparator/blob/118f11ddd940cd95341c4cc6a8718947e1ebaeff/src/sortingtraining/sortalgorythms/BubbleSort.java#L15

Could you please, for my good health consider changing iterators according to convention?

**Comment by pawelKapl** [comment]
Changed!
