### ISSUE TITLE
Always compare constant to variable

### ISSUE THREAD

**Issue by Augustyn** [darkonion/SortingComparator#5]
Despite inverse semantic it's logical operation that is NPE safe that more benefit, than semantic. Regime of NPE safe code should be priority.

https://github.com/darkonion/SortingComparator/blob/d83fc9ac36d37ff2646f68518a29cf8c1ecca474/src/sortingtraining/SortTester.java#L31

**Comment by pawelKapl** [comment]
Thanks, but it seem that you are looking at old revision, the newest one on development branch fixed it!! SortTester also is no longer SortTester I renamed it to SortCompMain, so you wont confuse it with testing class. 

https://github.com/darkonion/SortingComparator/commit/229482547c90cbd66e038dadc58b7e21505acb7e  Here you have the newest yesterdays commit!

**Comment by Augustyn** [comment]
ok
